### ISSUE TITLE
It would be handy to unlock only certain types

### ISSUE THREAD

**Issue by dmitrynovik** [Fody/Publicize#11]
It would be handy rather than "publicize everything" to specify only the desired types e.g. "I want to unlock only types Foo and Bar"

This stems from the fact that encapsulation is usually there for a reason, with a few exceptions.

**Comment by SimonCropp** [comment]
Would it be easier to just make those exceptions explicitly public, rather than take a dependency on a tool?

**Comment by dmitrynovik** [comment]
I'm not talking my code. When all code is yours, you don't need Fody Publicize as you are in full control of your own access modifiers. The problem is that when you consume 3rd party with internal or sealed types: you are intersting in unlocking only a few types which are relevant to you. My understanding is that this plugin makes everything public.

**Comment by SimonCropp** [comment]
no this project does not target 3rd part assemblies. it is the decision of the library owner to "make things public"

even theoretically processing a 3rd party lib would be difficult seeing as you are not guaranteed to have strong name keys
